@startuml Process
actor Customer
participant "Digital Manufacturing Platform" as DMP
database BigchainDB

Customer -> DMP: RequestPrintJob(QualityRequirement, Printer)
activate DMP
note left: Triggered via UI
group Chaincode
    DMP -> BigchainDB: Store Printing Job
    deactivate DMP
    activate BigchainDB
    BigchainDB -> DMP: TransactionID to Job
    deactivate BigchainDB
    activate DMP
    DMP -> Printer: Send Job(TransactionID to job)
    deactivate DMP
    activate Printer
    
end
Printer -> Printer: Execute Job
Printer -> DMP: UploadQualityReport
deactivate Printer
activate DMP
group Chaincode
    DMP -> BigchainDB: Store quality report
    deactivate DMP
    activate BigchainDB
    BigchainDB -> DMP: TransactionID to quality report

    deactivate BigchainDB
    activate DMP
    DMP -> DMP: EvaluateReport(KeyToReport)
end
    DMP-> Customer: Send Feedback
    deactivate DMP
@enduml
