@startuml
Customer -> DMP: RequestPrintJob(3DData)
database BigchainDB

note right: 3D Data, Which Evaluation Algorithm should be used
DMP -> BigchainDB: Store Printing Job
BigchainDB -> DMP: TransactionID to Job
DMP -> DMP: Choose Printer
DMP -> Printer: Send Job(TransactionID to job)
Printer -> Printer: Execute Job
group System boundary
    Printer -> BigchainDB: StoreQuality report
    Printer -> DMP: Done(KeyToReport)
    DMP-> BigchainDB: Load Algorithm
    DMP -> DMP: EvaluateReport(KeyToReport)
    DMP-> Customer: Send Feedback
end
@enduml
